### ISSUE TITLE
'Setting unknown property: craft\elements\db\EntryQuery::0' when Importing

### ISSUE THREAD

**Issue by strategyagency** [Rias500/craft-scout#31]
I've simplified my scout.php as much as possible:

```
<?php

return [
    "sync" => true,
    "application_id" => "removed",
    "admin_api_key" => "removed",
    "mappings" => [
        [
            'indexName' => 'pages',
            'elementType' => \craft\elements\Entry::class,
            'criteria' => [
                ['section' => 'contact']
            ]
        ]
    ],
];
```

But when running `./craft scout/index/import` I get an error:

```
Exception 'yii\base\UnknownPropertyException' with message 'Setting unknown property: craft\elements\db\EntryQuery::0'

in /path/vendor/yiisoft/yii2/base/Component.php:209

Stack trace:
#0 /path/vendor/craftcms/cms/src/elements/db/ElementQuery.php(425): yii\base\Component->__set('0', Array)
#1 /path/vendor/craftcms/cms/src/elements/db/EntryQuery.php(227): craft\elements\db\ElementQuery->__set('0', Array)
#2 /path/vendor/yiisoft/yii2/BaseYii.php(546): craft\elements\db\EntryQuery->__set('0', Array)
#3 /path/vendor/rias/craft-scout/src/models/AlgoliaIndex.php(247): yii\BaseYii::configure(Object(craft\elements\db\EntryQuery), Array)
#4 /path/vendor/rias/craft-scout/src/console/controllers/IndexController.php(76): rias\scout\models\AlgoliaIndex->getElementQuery()
#5 [internal function]: rias\scout\console\controllers\IndexController->actionImport('')
#6 /path/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#7 /path/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#8 /path/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('import', Array)
#9 /path/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('import', Array)
#10 /path/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('scout/index/imp...', Array)
#11 /path/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('scout/index/imp...', Array)
#12 /path/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#13 /path/craft(22): yii\base\Application->run()
#14 {main}
```

**Comment by strategyagency** [comment]
Improper formatting around criteria

```
'criteria' => [
        ['section' => 'contact']
]
```

should be

```
'criteria' => [
       'section' => ['contact']
]
```
