### ISSUE TITLE
Stuck task "Adding element to index" when entry contains Checkboxes field

### ISSUE THREAD

**Issue by elvdm** [Rias500/craft-scout#6]
Steps to reproduce:

1. Have Scout installed with no config file set on Craft CMS 3.0.0-RC14.
2. Add a Checkboxes field to your entry's field layout.
3. Save the entry (values in the field does not matter).
4. "Adding element to index" task appears as pending in the CP. It gets stuck and is never added to the queue table either (not sure how to clear it, actually).

No `phperrors.log` created, but this has appeared in `queue.log`:

```
2018-03-11 15:54:29 [127.0.0.1][1][-][error][UnexpectedValueException] UnexpectedValueException: Error at offset 0 of 2 bytes in /Users/emma/Sites/c3test/vendor/yiisoft/yii2-queue/src/serializers/PhpSerializer.php:32
Stack trace:
#0 [internal function]: ArrayObject->unserialize('[]')
#1 /Users/emma/Sites/c3test/vendor/yiisoft/yii2-queue/src/serializers/PhpSerializer.php(32): unserialize('O:28:"rias\\scou...')
#2 /Users/emma/Sites/c3test/vendor/yiisoft/yii2-queue/src/Queue.php(195): yii\queue\serializers\PhpSerializer->unserialize('O:28:"rias\\scou...')
#3 /Users/emma/Sites/c3test/vendor/yiisoft/yii2-queue/src/cli/Queue.php(139): yii\queue\Queue->handleMessage('4', 'O:28:"rias\\scou...', '300', 1)
#4 /Users/emma/Sites/c3test/vendor/craftcms/cms/src/queue/Queue.php(95): yii\queue\cli\Queue->handleMessage('4', 'O:28:"rias\\scou...', '300', 1)
#5 /Users/emma/Sites/c3test/vendor/craftcms/cms/src/controllers/QueueController.php(84): craft\queue\Queue->run()
#6 [internal function]: craft\controllers\QueueController->actionRun()
#7 /Users/emma/Sites/c3test/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#8 /Users/emma/Sites/c3test/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#9 /Users/emma/Sites/c3test/vendor/craftcms/cms/src/web/Controller.php(74): yii\base\Controller->runAction('run', Array)
#10 /Users/emma/Sites/c3test/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('run', Array)
#11 /Users/emma/Sites/c3test/vendor/craftcms/cms/src/web/Application.php(237): yii\base\Module->runAction('queue/run', Array)
#12 /Users/emma/Sites/c3test/vendor/craftcms/cms/src/web/Application.php(445): craft\web\Application->runAction('queue/run', Array)
#13 /Users/emma/Sites/c3test/vendor/craftcms/cms/src/web/Application.php(221): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#14 /Users/emma/Sites/c3test/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#15 /Users/emma/Sites/c3test/web/index.php(21): yii\base\Application->run()
#16 /Users/emma/.composer/vendor/laravel/valet/server.php(147): require('/Users/emma/Sit...')
#17 {main}
```

Task runs and clears self as expected if there is no Checkboxes field added to the entry.

**Comment by Rias500** [comment]
@elvdm I've changed some stuff around on how indexing works with the Queue, let me know if https://github.com/Rias500/craft-scout/releases/tag/0.3.0 fixes the issue!

**Comment by elvdm** [comment]
@Rias500 Thanks for the quick follow-up. Unfortunately the same issue is persisting.

**Comment by Rias500** [comment]
@elvdm seems like checkboxes are kind of a special fieldtype when they're serialized. The easiest way to fix this is by doing the following:

```php
return [
    'options' => (array) $entry->options,
];
```

This will make sure it's cast to an array before sending it off to the queue and algolia.

**Comment by elvdm** [comment]
@Rias500 Ah, fantastic. Thanks!
